language: java

jdk:
  - oraclejdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
